---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: image-docker=foxtail220/nginx_task31:~v11
    argocd-image-updater.argoproj.io/image-docker.update-strategy: digest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/FoxTail220/PlaysDev_lab.git
    targetRevision: main
    path: task31/helm_chart
    helm:
      parameters:
        - name: "replicaCount"
          value: "1"
        - name: "image.repository"
          value: foxtail220/nginx_task31
        - name: "image.tag"
          value: v1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true


