apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
  annotations:
    image-updater.quay.io/update-strategy: "registry"
spec:
  project: default
  source:
    repoURL: 'https://github.com/FoxTail220/PlaysDev_lab.git'
    path: 'task31/helm_chart'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: task31-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
