apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: loki
    release: loki
  name: storage-loki-0-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem

