apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-application
spec:
  replicas: 1
  selector:
    matchLabels:
      project: task31
  template:
    metadata:
      labels:
        project: task31
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
        - name: apache
          image: foxtail220/apache_task31:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-deployment
spec:
  type: NodePort
  selector:
    project: task31
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
