apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-application
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      project: task31
  template:
    metadata:
      labels:
        project: task31
    spec:
      containers:
        - name: nginx
          image: {{ .Values.containers.image_nginx }}
          ports:
            - containerPort: 80
        - name: apache
          image: {{ .Values.containers.image_apache }}
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-deployment
spec:
  type: NodePort
  selector:
    project: task31
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
