apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-k8s-application
  template:
    metadata:
      labels:
        app: my-k8s-application
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: foxtail220/nginx_task31
          ports:
            - containerPort: 80
        - name: apache
          image: foxtail220/apache_task31:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-deployment
spec:
  type: NodePort
  selector:
    app: my-k8s-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080