version: '3'

services:
  custom_apache:
    image: apache_custom
    container_name: custom_apache
    ports:
      - "8080:8080"
    command: echo "<?php phpinfo(); ?>" > /var/www/html/info.php

  custom_nginx:
    image: nginx_custom
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "8082:8082"
    command: nginx -g 'daemon off;'
    container_name: custom_nginx
    volumes:
      - /home/valera/docker/nginx_custom/ssl:/etc/nginx/ssl
