apiVersion: v1
kind: Service
metadata:
  name: my-web-deployment
spec:
  type: NodePort
  selector:
    project: task26
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
