global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          metric: "CPU"

  - job_name: 'external-server'
    static_configs:
      - targets: ['35.177.51.76:9100']
        labels:
          metric: "VM"
